### ISSUE TITLE
Documentation issue: calcTOAIrradRadRef()

### ISSUE THREAD

**Issue by fdetsch** [environmentalinformatics-marburg/satellite#13]
- Parameter 'rad_min' is not required in the function body and may be removed from documentation. Furthermore, description for parameter 'ref_max' is missing and should be added.
- Link to function `eSun` (section 'Details') is broken -> deprecated function call?

**Comment by tnauss** [comment]
What do you mean with "Link to function eSun (section 'Details') is broken -> deprecated function call?" I don't see such a link.

**Comment by fdetsch** [comment]
"By default, the resulting actual ESun will be normalized to a mean earth-sun distance to be compatible with other default results from eSun." (a link is attached to the last eSun)

**Comment by tnauss** [comment]
Nachtblind
