### ISSUE TITLE
CRAN check issue: agree to the CRAN repository policy 

### ISSUE THREAD

**Issue by fdetsch** [environmentalinformatics-marburg/satellite#18]
```r
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Environmental Informatics
<admin@environmentalinformatics-marburg.de>’
New submission
```
See [this solution](http://r.789695.n4.nabble.com/New-Submission-to-CRAN-note-td4643889.html).

**Comment by tim-salabim** [comment]
This is not a problem and can be irgnored

On 08.07.2015 16:23, Florian Detsch wrote:
> *  checking  CRAN  incoming  feasibility  ...  NOTE
> Maintainer:  ‘Environmental  Informatics
> <admin@environmentalinformatics-marburg.de>’
> New  submission
>
> See this solution 
> <http://r.789695.n4.nabble.com/New-Submission-to-CRAN-note-td4643889.html>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/environmentalinformatics-marburg/satellite/issues/18>.
>

-- 
#####################################
Tim Appelhans
Department of Geography
Environmental Informatics
Philipps Universität Marburg
Deutschhausstraße 12
35032 Marburg (Paketpost: 35037 Marburg)
Germany

Tel +49 (0) 6421 28-25957

http://environmentalinformatics-marburg.de/

**Comment by fdetsch** [comment]
Still, NOTEs are not desirable.
