### ISSUE TITLE
NAMESPACE

### ISSUE THREAD

**Issue by tnauss** [environmentalinformatics-marburg/satellite#23]
@Flo: why did you add

import(plyr)
import(methods)
useDynLib(satellite)

to NAMESPACE? Why not generating it automatically using roxygen?

**Comment by fdetsch** [comment]
Due to some C++ related issues. Roxygen eliminates some `import` calls required by **Rcpp**, so I disabled the creation of NAMESPACE via Roxygen (just like we had to do it for **remote**, hopefully this will be fixed some day...).
